name: ❌ Bug report
description: Report errors or unexpected behavior
labels: ❌ bug
body:
- type: checkboxes
  attributes:
      label: 🧐 Have you fully read the README and viewed similar issues?
      description: Please read the <a href="https://github.com/xManager-v2/xManager-Spotify/blob/main/README.md">README</a>. Also check the open and closed <a href="https://github.com/xManager-v2/xManager-Spotify/issues">issue</a> because your issue may have already been fixed.
      options:
        - label: I have read the README
          required: true
        - label: I have checked older issues, open and closed
          required: true
        - label: I did a clean install of xManager
          required: true
        - label: This is an xManager app issue -- NOT a Spotify mod issue
          required: true
- type: markdown
  attributes:
    value: "###"    
- type: textarea
  attributes:
    label: ℹ Information
    description: |
      - Device Model: e.g. <kbd>Pixel 7 Pro</kbd> 
      - Android Version: e.g. <kbd>Android 13</kbd>
      - ROM Version: e.g. <kbd>stock</kbd>
        - If using unmodified device, list as `stock`. If using a custom ROM, list ROM used, e.g. `LineageOS 20`
      - xManager Version: e.g. <kbd>4.1</kbd>
        - Open xManager, in the bottom section, click <kbd>About ℹ</kbd>
        - Report version # at top of screen
    placeholder: |
        - Device Model:  
        - Android Version:  
        - ROM Version:  
        - xManager Version:  
    value: |
        - Device Model:  
        - Android Version:  
        - ROM Version:  
        - xManager Version:  
    render: markdown   
  validations:
    required: true    
- type: textarea
  attributes:
    label: 📝 Description
    description: List steps to reproduce the error and details on what happens and what you expected to happen.
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: 📸 Screenshots
    description: Place any screenshots of the issue here if needed
  validations:
    required: false    
